### ISSUE TITLE
Unable to resolve symbol "List"

### ISSUE THREAD

**Issue by samuela** [t6/from-scala#1]
It seems that from-scala is not auto-importing things as the documentation implies:

```clojure
user=> ($ List & 1 2 3)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: List in this context, compiling:(NO_SOURCE_PATH:1:1) 
```

however

```clojure
user=> ($ scala.collection.immutable.List & 1 2 3)
#<$colon$colon List(1, 2, 3)>
```

works.

**Comment by samuela** [comment]
```(def List scala.collection.immutable.List)``` gives the advertised behavior.

**Comment by t6** [comment]
You're right.

It should work with ```(import 'scala.collection.immutable.List)``` (or the equivalent in your ns form) too.
